apiVersion: v1
kind: Pod
metadata:
  name: colorapp-configmap
  labels: 
    app: colorapp
spec:
  containers:
  - image: mmumshad/simple-webapp-color
    env:
    - name: APP_COLOR
      valueFrom: 
        configMapKeyRef:
          name: colorapp-config
          key: COLOR_ENV
    name: colorapp-configmap
    ports:
    - containerPort: 8080
