apiVersion: v1
kind: Pod
metadata:
  name: colorapp-secret
  labels: 
    app: colorapp
spec:
  containers:
  - image: mmumshad/simple-webapp-color
    env:
    - name: APP_KEY
      valueFrom: 
        secretKeyRef:
          name: app-secret-key
          key: appkey
    name: app-color-secret
    ports:
    - containerPort: 8080
