apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-hostpath
spec:
  capacity: 
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: localstorage
  hostPath:
    path: /tmp/mongodb
